### ISSUE TITLE
Setelah scan, langsung crash force close

### ISSUE THREAD

**Issue by fahmiyufrizal** [afarhansib/wabill#7]
Saya menggunakan Windows 11
Setelah dilakukan scan qr melalui localhost:8000, tiba tiba console wabill tertutup dengan sendirinya dan qr menjadi hilang dan loading
![Screenshot (27)](https://user-images.githubusercontent.com/60032856/141072368-5f3e5e4a-3187-4cb4-8eeb-3d1bacd982c7.png)

Bagaimana cara mengatasinya?

**Comment by afarhansib** [comment]
WhatsApp nya pakai fitur multi device?

**Comment by fahmiyufrizal** [comment]
Iya benar menggunakan multi-device. Apakah masih belum support?

**Comment by asepwaee** [comment]
Belum Support multidevice ya mas ?

**Comment by afarhansib** [comment]
> Belum Support multidevice ya mas ?

sudah, ada di branch testing
